import test from 'node:test';
import assert from 'node:assert/strict';
import {createEditor} from '../src/editor-core';
import {blank,node,createComponent,instantiate,parseDocument,updateNode} from '../src/model';
import {FontRegistry,attachFonts,fontIssue,validateFontDefinitions} from '../src/fonts';
import {renderScreenToSVG} from '../src/screen-svg';
import {revision} from '../src/agent';
import type {FontDefinition,FontLoader} from '../src/contracts';
const custom:FontDefinition={id:'editorial',name:'Editorial',variants:[{weight:400,source:{url:'/fonts/regular.woff2'},export:'embed'},{weight:700,source:{url:'/fonts/bold.woff2'},export:'embed'},{weight:400,style:'italic',source:{url:'/fonts/italic.woff2'},export:'embed'}]};
const loader=():FontLoader=>({async load(){},measure(t,f){return t.length*f.size*.5;},baseline(f,line){return f.size*line*.8;},async css(){return '';},dispose(){}});
function fixture(){const p=blank();p.nodes=[node('frame',{id:'frame',width:600,height:600}),node('text',{id:'text',parentId:'frame',text:'Texto que permanece editable',width:250,height:120})];return p;}
test('old v1/v2 documents and system/serif/mono remain valid; custom references survive reopening',()=>{const p=fixture();for(const f of ['system','serif','mono','editorial']){p.nodes[1].fontFamily=f;const reopened=parseDocument(JSON.stringify(p));assert.equal(reopened.nodes[1].fontFamily,f);assert.equal(reopened.nodes[1].text,p.nodes[1].text);}p.nodes[1].fontFamily='bad; color:red';assert.throws(()=>parseDocument(p),/Estilo/);});
test('font resources reject collisions, malformed sources and ambiguous or duplicate variants',()=>{assert.throws(()=>validateFontDefinitions([{...custom,id:'system'}]));assert.throws(()=>validateFontDefinitions([{...custom,variants:[custom.variants[0],custom.variants[0]]}]));assert.throws(()=>validateFontDefinitions([{...custom,variants:[{weight:400,source:{url:'javascript:alert(1)'}}]}]));assert.throws(()=>validateFontDefinitions([{...custom,variants:[{weight:400,source:{local:'Example'},export:'embed'}]}]));});
test('catalog loading is explicit, isolated and leaves document revisions/persistence untouched',async()=>{const changes:unknown[]=[],a=createEditor({document:fixture(),fonts:[custom],fontLoader:loader(),onChange:p=>changes.push(p)}),b=createEditor({document:fixture()});const before=await revision(a.getDocument());assert.equal(a.getFonts().find(f=>f.id==='editorial')!.variants[0].status,'registered');await a.loadFonts();assert.equal(a.getFonts().find(f=>f.id==='editorial')!.variants[0].status,'loaded');assert.equal(await revision(a.getDocument()),before);assert.equal(changes.length,0);assert.ok(!b.getFonts().some(f=>f.id==='editorial'));a.getFonts()[3].variants[0].status='error';assert.equal(a.getFonts()[3].variants[0].status,'loaded');a.destroy();b.destroy();});
test('missing variants and missing sources report clearly without replacing editable text',async()=>{const p=fixture();p.nodes[1].fontFamily='editorial';const a=createEditor({document:p,fonts:[custom],fontLoader:{...loader(),async load(){throw new Error('404 resource');}}});assert.equal(a.getFontIssues()[0].kind,'pending');await a.loadFonts();assert.equal(a.getFontIssues()[0].kind,'error');assert.equal(a.getDocument().nodes[1].fontFamily,'editorial');a.setFonts([]);assert.equal(a.getFontIssues()[0].kind,'missing');assert.equal(a.getDocument().nodes[1].text,p.nodes[1].text);a.destroy();});
test('agent discovers loaded variants and rejects invented families or synthetic weights atomically',async()=>{const a=createEditor({document:fixture(),fonts:[custom],fontLoader:loader()});await a.loadFonts();const catalog=await a.agent('catalog',{kind:'fonts'}) as any;assert.ok(catalog.fonts.find((f:any)=>f.id==='editorial').variants.every((v:any)=>v.status==='loaded'));const before=a.getDocument();for(const patch of [{fontFamily:'invented'},{fontFamily:'editorial',fontWeight:600}]){const response=await a.agent('apply',{expectedRevision:await revision(a.getDocument()),operations:[{op:'update',id:'text',patch}],dryRun:true}) as any;assert.equal(response.ok,false);assert.deepEqual(a.getDocument(),before);}const response=await a.agent('apply',{expectedRevision:await revision(a.getDocument()),operations:[{op:'update',id:'text',patch:{fontFamily:'editorial',fontWeight:400,fontStyle:'italic'}}]}) as any;assert.equal(response.ok,true);assert.equal(a.getDocument().nodes[1].fontStyle,'italic');a.destroy();});
test('component inheritance, local overrides and undo/redo persist',async()=>{const p=fixture();p.nodes[1].fontFamily='editorial';p.nodes[1].fontStyle='italic';const c=createComponent(p,'text');instantiate(p,c.id,'frame',0,200);const a=createEditor({document:p,fonts:[custom],fontLoader:loader()});await a.loadFonts();const instance=a.getDocument().nodes.find(n=>n.instanceOf===c.id)!;a.apply([{op:'update',id:'text',patch:{fontWeight:700,fontStyle:'normal'}}]);assert.equal(a.getDocument().nodes.find(n=>n.id===instance.id)!.fontWeight,700);a.apply([{op:'update',id:instance.id,patch:{fontWeight:400,fontStyle:'italic'}}]);a.undo();assert.equal(a.getDocument().nodes.find(n=>n.id===instance.id)!.fontWeight,700);a.redo();const reopened=createEditor({document:JSON.parse(JSON.stringify(a.getDocument())),fonts:[custom],fontLoader:loader()});await reopened.loadFonts();assert.equal(reopened.getDocument().nodes.find(n=>n.id===instance.id)!.fontStyle,'italic');assert.equal(reopened.getFontIssues().length,0);a.destroy();reopened.destroy();});
test('load results after replacing the catalog cannot admit the previous font',async()=>{const finishes:(()=>void)[]=[];const registry=new FontRegistry([custom]);registry.bind({...loader(),load:()=>new Promise<void>(r=>{finishes.push(r);})});const work=registry.load(['editorial']);registry.set([]);finishes.forEach(f=>f());await assert.rejects(work,/cambió/);assert.ok(!registry.list().some(f=>f.id==='editorial'));registry.dispose();});
test('headless SVG refuses approximate custom metrics or missing fonts',()=>{const p=fixture();p.nodes[1].fontFamily='editorial';assert.throws(()=>renderScreenToSVG(p),/Fuente ausente/);const r=new FontRegistry([custom]);attachFonts(p,r);assert.equal(fontIssue(p,p.nodes[1])!.kind,'pending');});

test('custom typography tokens expose the resolved face and preserve actual style after reopening',async()=>{const p=fixture();for(const mode of ['light','dark'] as const)p.designThemes.project.modes[mode].typography.custom={name:'Editorial',fontFamily:'editorial',fontStyle:'italic',fontWeight:400,fontSize:36,lineHeight:1.3};p.nodes[1].typographyToken='custom';const a=createEditor({document:p,fonts:[custom],fontLoader:loader()});await a.loadFonts();const context=await a.agent('context',{scope:'text'}) as any;assert.equal(context.context.nodes[0].typography.fontStyle,'italic');assert.equal(a.getFontIssues().length,0);const reopened=parseDocument(JSON.stringify(a.getDocument()));assert.equal(reopened.designThemes.project.modes.light.typography.custom.fontFamily,'editorial');a.destroy();});

test('manual typography edits detach the active token and reject unavailable variants',async()=>{const p=fixture();for(const mode of ['light','dark'] as const)p.designThemes.project.modes[mode].typography.custom={name:'Editorial',fontFamily:'editorial',fontWeight:400,fontSize:36,lineHeight:1.3};p.nodes[1].typographyToken='custom';const a=createEditor({document:p,fonts:[custom],fontLoader:loader()});await a.loadFonts();assert.throws(()=>a.apply([{op:'update',id:'text',patch:{fontFamily:'invented'}}]),/Fuente ausente/);a.apply([{op:'update',id:'text',patch:{fontStyle:'italic'}}]);const n=a.getDocument().nodes[1];assert.equal(n.typographyToken,undefined);assert.equal(n.fontFamily,'editorial');assert.equal(n.fontSize,36);assert.equal(n.fontStyle,'italic');a.undo();assert.equal(a.getDocument().nodes[1].typographyToken,'custom');a.destroy();});
test('adding catalog entries keeps loaded faces while embedding only the variants in use',async()=>{const r=new FontRegistry([{...custom,variants:[custom.variants[0],{weight:800,source:{local:'Private Face'}}]}]);let used:FontDefinition[]=[];r.bind({...loader(),async css(ds){used=ds;return 'embedded';}});await r.load();r.register([{id:'new-face',name:'New',variants:[{weight:400,source:{url:'new.ttf'}}]}]);assert.equal(r.list().find(f=>f.id==='editorial')!.variants[0].status,'loaded');assert.ok((await r.css('embed',['editorial'],[{fontFamily:'editorial',fontWeight:400}])).includes('embedded'));assert.equal(used[0].variants.length,1);await assert.rejects(r.css('embed',['editorial']),/export:embed/);r.dispose();});
test('browser imports preserve families and distinguish styles in their typography tokens',async()=>{const {importDOM}=await import('../src/dom-import');const {resolveNodeStyle}=await import('../src/themes');const p=blank();const r=new FontRegistry([custom]);attachFonts(p,r);const input={format:'codaru-dom-snapshot',version:1,url:'https://example.test',viewport:{width:600,height:600},height:600,body:{bg:'#fff'},elements:[{i:1,p:null,kind:'text',tag:'p',x:20,y:20,w:200,h:80,text:'Regular',font:{family:'Editorial',size:24,weight:400,lineHeight:31}},{i:2,p:null,kind:'text',tag:'em',x:20,y:100,w:200,h:80,text:'Italic',font:{family:'Editorial',size:24,weight:400,lineHeight:31,italic:true}},{i:3,p:null,kind:'text',tag:'p',x:20,y:200,w:200,h:80,text:'Missing',font:{family:'Unknown Original',size:24,weight:400,lineHeight:31}}]};importDOM(p,input);const texts=p.nodes.filter(n=>n.type==='text');assert.equal(resolveNodeStyle(p,texts[0]).fontFamily,'editorial');assert.equal(resolveNodeStyle(p,texts[1]).fontStyle,'italic');assert.notEqual(texts[0].typographyToken,texts[1].typographyToken);assert.match(resolveNodeStyle(p,texts[2]).fontFamily!,/^font-unknown-original/);});

test('font validation runs after component propagation so local styles cannot become silent unavailable variants',async()=>{const p=fixture();p.nodes[1].fontFamily='editorial';const c=createComponent(p,'text'),instance=instantiate(p,c.id,'frame',0,200);updateNode(p,instance,{fontStyle:'italic'});const alternate:FontDefinition={id:'alternate',name:'Only regular',variants:[{weight:400,source:{url:'/alternate.ttf'}}]};const a=createEditor({document:p,fonts:[custom,alternate],fontLoader:loader()});await a.loadFonts();const before=a.getDocument();assert.throws(()=>a.apply([{op:'update',id:'text',patch:{fontFamily:'alternate'}}]),/Variante ausente/);assert.deepEqual(a.getDocument(),before);const result=await a.agent('apply',{expectedRevision:await revision(before),operations:[{op:'update',id:'text',patch:{fontFamily:'alternate'}}],dryRun:true}) as any;assert.equal(result.ok,false);assert.deepEqual(a.getDocument(),before);a.destroy();});

test('agent import transactions retain the host font catalog across their draft clone',async()=>{const a=createEditor({document:blank(),fonts:[custom],fontLoader:loader()});await a.loadFonts();const data={format:'codaru-dom-snapshot',version:1,url:'https://example.test',viewport:{width:600,height:600},height:600,body:{bg:'#fff'},elements:[{i:1,p:null,kind:'text',tag:'p',x:20,y:20,w:200,h:80,text:'Imported custom face',font:{family:'Editorial',size:24,weight:400,lineHeight:31,italic:true}}]};const result=await a.agent('apply',{expectedRevision:await revision(a.getDocument()),operations:[{op:'dom',data}]}) as any;assert.equal(result.ok,true,JSON.stringify(result.error));const n=a.getDocument().nodes.find(n=>n.text==='Imported custom face')!;assert.equal(n.fontFamily,'editorial');assert.equal(a.getFontIssues().length,0);a.destroy();});
