import test from 'node:test';
import assert from 'node:assert/strict';
import { createHash } from 'node:crypto';
import { createEditor, getEditorSession } from '../src/editor-core';
import { blank, node, validate } from '../src/model';
import { emptyIdentityLab, identityTargetRevision } from '../src/identity';
import type { IdentityDirection, IdentityEvidence, IdentityServices } from '../src/contracts';
const png='data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVQIHWP4z8DwHwAFgAI/ScLttAAAAABJRU5ErkJggg==';
const direction:IdentityDirection={id:'own',name:'Propia',intent:'Elegante con cultura',frameIds:['desktop','mobile'],styleIds:[],status:'exploring'};
function editor(services:IdentityServices={}){const p=blank();p.nodes=[node('frame',{id:'desktop',role:'screen'}),node('frame',{id:'mobile',role:'screen'}),node('text',{id:'title',parentId:'desktop',text:'Único'})];return createEditor({document:p,identityServices:services});}
function previews(request:{targetRevision:string}):IdentityEvidence[]{return direction.frameIds.map(frameId=>({revision:request.targetRevision,frameId,dataURL:png,width:1,height:1}));}
const verdict={summary:'Lectura clara; composición por mejorar.',findings:[{criterion:'Elegancia',assessment:'needs_work' as const,reason:'La jerarquía es demasiado densa.',nodeIds:['title']}],evaluator:{provider:'IDE',model:'real-vision-model'}};
function reviewServices():IdentityServices{return {render:async r=>previews(r),review:async()=>verdict};}
test('optional laboratory survives v1/v2 import, undo and independent consumers',()=>{const e=editor(),other=editor();assert.equal(e.getIdentityLab(),null);e.updateIdentityBrief({intent:'Deseo y cultura',qualities:['elegancia'],avoid:['genérico']});const lab=e.getIdentityLab()!;lab.brief.intent='outside';assert.equal(e.getIdentityLab()!.brief.intent,'Deseo y cultura');e.undo();assert.equal(e.getIdentityLab(),null);e.redo();assert.equal(other.getIdentityLab(),null);const legacy={...e.getDocument(),version:1};assert.equal(validate(legacy).identityLab!.brief.intent,'Deseo y cultura');const packed=e.exportIdentity();packed.document.nodes[0].name='outside';assert.notEqual(e.getDocument().nodes[0].name,'outside');assert.equal(packed.lab.format,'codaru-identity/1');});
test('strict validation rejects unsafe IDs, oversized content, unknown keys and missing targets atomically',()=>{const e=editor();assert.throws(()=>e.updateIdentityBrief({intent:'x'.repeat(4001)}));assert.throws(()=>e.applyIdentity({op:'identity.brief.set',patch:{unknown:1}} as never));assert.equal(e.getIdentityLab(),null);assert.throws(()=>e.upsertIdentityDirection({...direction,id:'__proto__'}));assert.throws(()=>e.upsertIdentityDirection({...direction,frameIds:['missing']}));assert.throws(()=>e.upsertIdentityDirection({...direction,styleIds:['fake']}));assert.equal(e.getIdentityLab(),null);e.upsertIdentityDirection(direction);assert.throws(()=>e.apply([{op:'identity.brief.set',patch:{intent:'atomic'}},{op:'identity.reference.put',reference:{id:'r',title:'R',source:'javascript:alert(1)',kind:'visual',observations:'',status:'accepted'}}]));assert.equal(e.getIdentityLab()!.brief.intent,'');});
test('target SHA-256 includes actual node content and brief but excludes review history',()=>{const e=editor();e.upsertIdentityDirection(direction);const p=e.getDocument(),d=p.identityLab!.directions[0],included=new Set(['desktop','mobile','title']);const basis={direction:d,nodes:p.nodes.filter(n=>included.has(n.id)),themes:p.designThemes,theme:p.theme,activeThemeId:p.activeThemeId,styles:[],brief:p.identityLab!.brief,references:[]};assert.equal(identityTargetRevision(p,d),createHash('sha256').update(JSON.stringify(basis)).digest('hex'));});
test('research and explore store isolated proposals without replacing approved work or changing geometry',async()=>{const e=editor({research:async r=>{r.document.nodes[0].text='outside';return {references:[{id:'ref',title:'Hilván',source:'https://sic.cultura.gob.mx/',author:'Autoría documentada',community:'Amealco',kind:'cultural',observations:'Una técnica; no un glifo.',status:'accepted'}]};},explore:async()=>({directions:[{...direction,status:'selected'}]})});const before=e.getDocument().nodes;await e.requestIdentity({action:'research',instruction:'Procedencia'});assert.equal(e.getIdentityLab()!.references[0].status,'proposed');await e.requestIdentity({action:'explore'});assert.equal(e.getIdentityLab()!.directions[0].status,'exploring');assert.deepEqual(e.getDocument().nodes,before);await assert.rejects(e.requestIdentity({action:'research'}),/reemplazar/);await assert.rejects(e.requestIdentity({action:'explore'}),/reemplazar/);});
test('visual critique requires all actual frames, exact revision and evaluator; storing it does not self-invalidate',async()=>{const e=editor(reviewServices());e.upsertIdentityDirection(direction);await e.requestIdentity({action:'review',directionId:'own'});assert.equal(e.getIdentityLab()!.critiques.length,1);assert.deepEqual(e.getIdentityState().issues,[]);e.apply([{op:'update',id:'title',patch:{text:'Ahora distinto'}}]);assert.ok(e.getIdentityState().issues.some(i=>i.kind==='stale_review'));e.undo();assert.deepEqual(e.getIdentityState().issues,[]);const cases:IdentityServices[]=[{render:async r=>previews(r).slice(0,1),review:async()=>verdict},{render:async r=>previews(r).map(v=>({...v,revision:'f'.repeat(64)})),review:async()=>verdict},{render:async r=>previews(r).map(v=>({...v,dataURL:'data:image/png;base64,iVBORw0KGgo='})),review:async()=>verdict},{render:async r=>previews(r).map(v=>({...v,width:2})),review:async()=>verdict},{render:async r=>previews(r),review:async()=>({...verdict,evaluator:{provider:'',model:''}})}];for(const services of cases){const bad=editor(services);bad.upsertIdentityDirection(direction);await assert.rejects(bad.requestIdentity({action:'review',directionId:'own'}));assert.equal(bad.getIdentityLab()!.critiques.length,0);}});
test('late service responses fail after an edit, busy draft, service replacement or destroy',async()=>{for(const mode of ['edit','busy','services','destroy']){let resolve!:(value:{directions:IdentityDirection[]})=>void,started!:()=>void;const ready=new Promise<void>(r=>started=r);const e=editor({explore:async()=>{started();return new Promise(r=>resolve=r);}});let busy=false;getEditorSession(e).bindExtension({flush(){},dispose(){},isBusy:()=>busy});const pending=e.requestIdentity({action:'explore'});await ready;if(mode==='edit')e.updateIdentityBrief({intent:'Manual'});if(mode==='busy')busy=true;if(mode==='services')e.setIdentityServices({});if(mode==='destroy')e.destroy();resolve({directions:[direction]});await assert.rejects(pending,/obsoleta|ocupado|desmontado/);if(mode!=='destroy')assert.equal(e.getIdentityLab()?.directions.length??0,0);}});
test('refinement uses selected existing descendants, keeps proposal separate and flags later changes',async()=>{const e=editor({refine:async()=>({proposal:'Mover la navegación al borde superior, respetando la tipografía.'})});e.upsertIdentityDirection(direction);await assert.rejects(e.requestIdentity({action:'refine',directionId:'own',nodeIds:['missing'],instruction:'Más claro'}));await assert.rejects(e.requestIdentity({action:'refine',directionId:'own',nodeIds:['title'],instruction:''}));const before=e.getDocument().nodes;await e.requestIdentity({action:'refine',directionId:'own',nodeIds:['title'],instruction:'Más claro'});assert.deepEqual(e.getDocument().nodes,before);assert.equal(e.getIdentityLab()!.refinements[0].status,'proposed');e.updateIdentityBrief({intent:'Otra intención'});assert.ok(e.getIdentityState().issues.some(i=>i.kind==='stale_refinement'));});
test('deleted targets and references preserve historical evidence with explicit issues',async()=>{const e=editor(reviewServices());e.upsertIdentityReference({id:'source',title:'Fuente',source:'https://example.org/',kind:'cultural',observations:'Contexto',status:'accepted'});e.upsertIdentityDirection({...direction,referenceIds:['source']});e.addIdentityDecision({id:'decision',directionId:'own',criterion:'Elegancia',observation:'Mejor, aún denso.',next:'Más aire',outcome:'revise',author:'Persona',at:'2026-10-09T18:00:00Z'});await e.requestIdentity({action:'review',directionId:'own'});assert.throws(()=>e.addIdentityDecision({id:'decision',criterion:'Otro',observation:'No reemplazar',next:'',outcome:'keep',author:'Otro',at:'2026-10-09T18:00:00Z'}));e.applyIdentity({op:'identity.reference.remove',id:'source'});assert.ok(e.getIdentityState().issues.some(i=>i.kind==='missing_reference'));e.apply([{op:'remove',ids:['desktop']}]);assert.ok(e.getIdentityState().issues.some(i=>i.kind==='missing_frame'));assert.ok(e.getIdentityState().issues.some(i=>i.kind==='missing_node'));e.applyIdentity({op:'identity.direction.remove',id:'own'});assert.equal(e.getIdentityLab()!.decisions.length,1);assert.equal(e.getIdentityLab()!.critiques.length,1);assert.ok(e.getIdentityState().issues.some(i=>i.kind==='missing_direction'));});
test('CLI uses shared operations with expectedRevision and exposes bounded context',async()=>{const e=editor();const c=await e.agent('context');const rev=c.context!.revision;const result=await e.agent('apply',{expectedRevision:rev,operations:[{op:'identity.brief.set',patch:{intent:'Desde CLI'}}]});assert.equal(result.ok,true);const conflict=await e.agent('apply',{expectedRevision:rev,operations:[{op:'identity.brief.set',patch:{intent:'Antiguo'}}]});assert.equal(conflict.ok,false);assert.equal(conflict.error!.code,'revision_conflict');const out=await e.agent('context');assert.equal((out.context!.identity as {brief:{intent:string}}).brief.intent,'Desde CLI');const schema=await e.agent('schema');assert.ok(JSON.stringify(schema).includes('identity.brief.set'));});
test('extension lifecycle flushes drafts on destroy; failed flush leaves session recoverable',()=>{const e=editor();let disposed=false,fail=true;getEditorSession(e).bindExtension({flush(){if(fail)throw new Error('No perder borrador');e.updateIdentityBrief({intent:'Texto enfocado'});},dispose(){disposed=true;}});assert.throws(()=>e.destroy(),/borrador/);assert.equal(disposed,false);assert.equal(e.getIdentityLab(),null);fail=false;const p=e.destroy();assert.equal(p.identityLab!.brief.intent,'Texto enfocado');assert.equal(disposed,true);assert.deepEqual(e.destroy(),p);});
test('render/evaluator snapshots cannot rewrite direction bindings or pixels retained for the critique',async()=>{const e=editor({render:async r=>{r.document.nodes[0].name='tampered';r.direction.frameIds=[];return previews(r);},review:async r=>{assert.equal(r.document.nodes[0].name,'Pantalla');r.evidence[0].dataURL='changed by provider';r.direction.name='tampered';return verdict;}});e.upsertIdentityDirection(direction);await e.requestIdentity({action:'review',directionId:'own'});assert.deepEqual(e.getIdentityLab()!.directions[0],direction);assert.equal(e.getIdentityLab()!.critiques[0].evidence[0].dataURL,png);});
test('busy drafts block CLI and direct requests; service capability changes notify without dirtying document',async()=>{const e=editor();let busy=true,notifications=0;e.subscribe(()=>notifications++);const original=e.getDocument();const unbind=getEditorSession(e).bindExtension({flush(){},dispose(){},isBusy:()=>busy});const c=await e.agent('context');const result=await e.agent('apply',{expectedRevision:c.context!.revision,operations:[{op:'identity.brief.set',patch:{intent:'No pisar borrador'}}]});assert.equal(result.error!.code,'editor_busy');await assert.rejects(e.requestIdentity({action:'research'}),/ocupado/);const before=notifications;e.setIdentityServices({research:async()=>({references:[]})});assert.ok(notifications>before);assert.deepEqual(e.getDocument(),original);busy=false;unbind();const request=await e.requestIdentity({action:'research'});assert.deepEqual(request.ids,[]);assert.equal(e.getIdentityLab(),null);});
