import { test, expect } from '@playwright/test';
import { readFileSync } from 'node:fs';
const data=JSON.parse(readFileSync('examples/aru-music/assets/musaru-app.aru.codaru.json','utf8'));
test('full editor imports prepared ARU files and delegates editing without writing the document',async({page})=>{
  await page.goto('/tests/fixtures/embed.html');await page.waitForFunction(()=>!!(window as any).embedTest);
  await page.evaluate(()=>{const t=(window as any).embedTest;(window as any).illustrationRequests=[];t.mount('aru',{documentName:'ARU host',onIllustrationRequest:(request:any)=>{(window as any).illustrationRequests.push(request);}});});
  await page.waitForFunction(()=>!!(window as any).embedTest.records.aru.api);
  const frame=page.frameLocator('iframe[data-embed="aru"]');
  await frame.locator('#image-file').setInputFiles({name:'musaru-app.aru.codaru.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(data))});
  await expect(frame.getByRole('button',{name:'Editar ilustración en el IDE'})).toBeEnabled();
  const before=await page.evaluate(()=>(window as any).embedTest.records.aru.api.getDocument());
  await frame.getByRole('button',{name:'Editar ilustración en el IDE'}).click();
  const requests=await page.evaluate(()=>(window as any).illustrationRequests);
  expect(requests[0].source.text).toBe(data.source);expect(requests[0].source.filename).toBe(data.filename);
  expect(await page.evaluate(()=>(window as any).embedTest.records.aru.api.getDocument())).toEqual(before);
});
test('ARU imports, host intent, source download, mobile asset source and undo work in fragments', async ({page})=>{
  await page.goto('/tests/fixtures/modular.html');await page.waitForFunction(()=>!!(window as any).modularTest);
  await page.evaluate(data=>{const t=(window as any).modularTest,a=t.mount('a'),b=t.mount('b');
    a.editor.apply([{op:'aru',id:'aru-logo',data,parentId:'a-frame',width:96}]);
    a.editor.select(['aru-logo']);(window as any).aruBefore=a.editor.getDocument();
  },data);
  const panel=page.locator('[data-instance="a"] [data-codaru-part="inspector"]');
  await expect(panel.getByRole('button',{name:'Editar ilustración en el IDE'})).toBeDisabled();
  const download=page.waitForEvent('download');await panel.getByRole('button',{name:'Exportar fuente ARU'}).click();
  expect((await download).suggestedFilename()).toBe('musaru-app.aru');
  const exported=await page.evaluate(async()=>{const t=(window as any).modularTest;const result=await t.records.a.editor.exportAsset({ids:['aru-logo'],format:'assets',width:48});return result.files;});
  expect(exported.some((f:any)=>f.path==='source/aru/aru-logo-musaru_app.aru')).toBe(true);
  expect(exported.some((f:any)=>f.path.includes('xxxhdpi'))).toBe(true);
  await page.evaluate(()=>{const t=(window as any).modularTest; if(JSON.stringify(t.records.a.editor.getDocument())!==JSON.stringify((window as any).aruBefore))throw new Error('Export mutated document');t.records.a.editor.undo();});
  await expect(panel.getByRole('button',{name:'Exportar fuente ARU'})).toHaveCount(0);
  expect(await page.evaluate(()=>(window as any).modularTest.records.b.editor.getDocument().nodes.some((n:any)=>n.aruSource))).toBe(false);
});
test('music fixture opens original ARU in host, animates in presentation and keeps photos local',async({page})=>{
  await page.goto('/examples/aru-music/index.html');await page.waitForFunction(()=>!!(window as any).aruMusic);
  await page.getByRole('button',{name:'Icono de app',exact:true}).click();
  await page.getByRole('button',{name:'Editar ilustración en el IDE'}).click();
  await expect(page.locator('#source-title')).toHaveText('musaru-app.aru');
  await expect(page.locator('#source-code')).toContainText('group record');
  await page.getByRole('button',{name:'Cerrar',exact:true}).click();
  await page.getByRole('button',{name:'Presentar',exact:true}).click();
  await expect(page.locator('#preview-canvas')).toBeVisible();
  const result=await page.locator('#preview-canvas').evaluate(el=>({animations:el.getAnimations({subtree:true}).length,images:[...el.querySelectorAll('img')].map(i=>i.src)}));
  expect(result.animations).toBeGreaterThan(0);expect(result.images.length).toBeGreaterThanOrEqual(3);expect(result.images.every(src=>src.startsWith('data:image/'))).toBe(true);
  await page.locator('#preview-canvas [data-node="hero-cta-label"]').click();
  await expect(page.locator('#preview-select')).toHaveValue('music-mobile');
  await expect(page.locator('#preview-canvas > *')).toHaveCount(1);
  await page.locator('#preview-canvas [data-target="music-desktop"]').click();
  await expect(page.locator('#preview-select')).toHaveValue('music-desktop');
  await expect(page.locator('#preview-canvas > *')).toHaveCount(1);
  await page.keyboard.press('Escape');await expect(page.locator('#preview-canvas')).toHaveCount(0);
});
