import { test, expect, type Page } from '@playwright/test';

const state=(page:Page)=>page.evaluate(()=>(window as any).codaru.getDocument());
const button=async(page:Page)=>(await state(page)).nodes.find((n:any)=>n.id==='primary-button');
test.beforeEach(async({page})=>{await page.goto('/');await expect(page.locator('[data-layer="screen-login"]')).toBeVisible();});

test('the fill picker edits color, transparency, theme tokens and gradients with one undo step each',async({page})=>{
  await page.locator('[data-layer="primary-button"]').click();
  await page.getByRole('button',{name:'Relleno: color'}).click();
  const picker=page.getByRole('dialog',{name:'Selector de color'});await expect(picker).toBeVisible();
  await expect(picker.getByLabel('HEX')).toHaveValue('@primary');
  await picker.getByLabel('HEX').fill('112233');await picker.getByLabel('HEX').press('Enter');
  expect((await button(page)).fill).toBe('#112233');await expect(picker).toBeVisible();
  await picker.getByLabel('Opacidad',{exact:true}).fill('50');
  expect((await button(page)).fill).toBe('#11223380');
  expect(await page.locator('#artboards [data-node="primary-button"]').evaluate(el=>getComputedStyle(el).backgroundColor)).toBe('rgba(17, 34, 51, 0.5)');
  const area=(await picker.getByLabel('Saturación y brillo').boundingBox())!;
  await page.mouse.move(area.x+area.width-20,area.y+20);await page.mouse.down();await page.mouse.move(area.x+area.width/2,area.y+20,{steps:3});
  expect((await button(page)).fill).toBe('#11223380');
  await page.mouse.up();
  const dragged=(await button(page)).fill;expect(dragged).toMatch(/^#[0-9a-f]{6}80$/);expect(dragged).not.toBe('#11223380');
  await page.getByRole('button',{name:'Deshacer · ⌘Z',exact:true}).click();expect((await button(page)).fill).toBe('#11223380');
  await page.getByRole('button',{name:'Relleno: color'}).click();
  await picker.getByRole('button',{name:'Token accent'}).click();expect((await button(page)).fill).toBe('@accent');
  await picker.getByRole('button',{name:'Sin color (transparente)'}).click();expect((await button(page)).fill).toBe('transparent');
  await picker.getByLabel('HEX').fill('no');await picker.getByLabel('HEX').press('Enter');expect((await button(page)).fill).toBe('transparent');
  await picker.getByLabel('Canal R').fill('255');await picker.getByLabel('Canal R').press('Tab');
  expect((await button(page)).fill).toMatch(/^#ff[0-9a-f]{4}$/);
  await picker.getByRole('tab',{name:'Degradado'}).click();
  await picker.getByRole('button',{name:'Marca',exact:true}).click();
  expect((await button(page)).fillToken).toBe('brand');await expect(page.getByLabel('Tipo',{exact:true})).toHaveValue('token:brand');
  await picker.getByRole('button',{name:'Laguna',exact:true}).click();
  let node=await button(page);
  expect(node).toMatchObject({gradient:'linear',gradientAngle:90,fill:'#2a7b9b',gradientEnd:'#eddd53',gradientStops:[{color:'#2a7b9b',position:0},{color:'#57c785',position:50},{color:'#eddd53',position:100}]});
  expect(node.fillToken).toBeUndefined();
  expect(await page.locator('#artboards [data-node="primary-button"]').evaluate(el=>getComputedStyle(el).backgroundImage)).toContain('rgb(87, 199, 133) 50%');
  await expect(page.getByRole('button',{name:'Editar degradado'})).toBeVisible();await expect(page.getByLabel('Relleno: valor',{exact:true})).toHaveCount(0);
  const bar=(await picker.getByLabel('Paradas del degradado').boundingBox())!;
  await page.mouse.click(bar.x+bar.width*.25,bar.y+bar.height/2);
  node=await button(page);expect(node.gradientStops).toHaveLength(4);expect(node.gradientStops[1].position).toBe(25);
  await expect(picker.getByLabel('Posición de la parada')).toHaveValue('25');
  await picker.getByLabel('HEX').fill('#ff0000');await picker.getByLabel('HEX').press('Enter');
  await picker.getByLabel('Posición de la parada').fill('70');await picker.getByLabel('Posición de la parada').press('Tab');
  node=await button(page);expect(node.gradientStops.map((stop:any)=>[stop.color,stop.position])).toEqual([['#2a7b9b',0],['#57c785',50],['#ff0000',70],['#eddd53',100]]);
  const handle=(await picker.getByRole('button',{name:'Parada 1, 0%'}).boundingBox())!;
  await page.mouse.move(handle.x+handle.width/2,handle.y+handle.height/2);await page.mouse.down();await page.mouse.move(bar.x+bar.width*.2,bar.y+bar.height/2,{steps:3});await page.mouse.up();
  expect((await button(page)).gradientStops[0].position).toBe(20);
  await picker.getByRole('button',{name:'Quitar parada'}).click();
  expect((await button(page)).gradientStops).toHaveLength(3);
  await picker.getByRole('button',{name:'Radial'}).click();expect((await button(page)).gradient).toBe('radial');await expect(picker.getByLabel('Ángulo del degradado')).toBeDisabled();
  await picker.getByRole('button',{name:'Lineal'}).click();
  await picker.getByLabel('Ángulo del degradado').fill('45');await picker.getByLabel('Ángulo del degradado').press('Tab');
  expect((await button(page)).gradientAngle).toBe(45);
  await picker.getByRole('button',{name:'Token accent'}).click();
  expect((await button(page)).gradientStops.some((stop:any)=>stop.color==='@accent')).toBe(true);
  const gradient=await button(page);
  await picker.getByRole('tab',{name:'Sólido'}).click();
  expect(await button(page)).toEqual(gradient);
  await picker.getByLabel('HEX').fill('#123456');await picker.getByLabel('HEX').press('Enter');
  node=await button(page);expect(node.gradient).toBe('none');expect(node.gradientStops).toBeUndefined();expect(node.fill).toBe('#123456');
  await page.keyboard.press('Escape');await expect(picker).toHaveCount(0);
  await page.getByRole('button',{name:'Deshacer · ⌘Z',exact:true}).click();expect(await button(page)).toEqual(gradient);
  await page.getByRole('button',{name:'Editar degradado'}).click();await expect(picker.getByRole('tab',{name:'Degradado'})).toHaveAttribute('aria-selected','true');
  await page.keyboard.press('Escape');
  await page.getByRole('button',{name:'Texto: color'}).click();await expect(picker).toBeVisible();await expect(picker.getByRole('tab')).toHaveCount(0);
  await page.locator('#stage').click({position:{x:5,y:5}});await expect(picker).toHaveCount(0);
});

test('theme palette, theme editor tokens and gradient stops use the same picker',async({page})=>{
  await page.getByRole('button',{name:'Color del tema primary'}).click();
  const picker=page.getByRole('dialog',{name:'Selector de color'});
  await picker.getByLabel('HEX').fill('#0a84ff');await picker.getByLabel('HEX').press('Enter');
  expect((await state(page)).themes.light.primary).toBe('#0a84ff');
  await page.keyboard.press('Escape');
  await page.getByRole('button',{name:'Temas',exact:true}).click();
  const themes=page.getByRole('dialog',{name:'Editor de temas'});
  await themes.getByRole('button',{name:'Valor del color: selector'}).click();
  await expect(picker.getByRole('button',{name:'Token primary'})).toHaveCount(0);
  await picker.getByLabel('Tono').fill('120');
  const green=(await state(page)).designThemes.project.modes.light.colors.primary;
  expect(green).not.toBe('#0a84ff');expect(parseInt(green.slice(3,5),16)).toBeGreaterThan(parseInt(green.slice(1,3),16));
  await page.keyboard.press('Escape');await expect(themes).toBeVisible();
  await themes.getByRole('button',{name:'Degradados',exact:true}).click();
  await themes.getByRole('button',{name:'Color parada 2: selector'}).click();
  await picker.getByRole('button',{name:'Token accent'}).click();
  expect((await state(page)).designThemes.project.modes.light.gradients.brand.stops[1].color).toBe('@accent');
  await themes.getByRole('button',{name:'Listo',exact:true}).click();await expect(picker).toHaveCount(0);
});
