import {test,expect} from '@playwright/test';
test.beforeEach(async({page})=>{await page.goto('/examples/fonts-host.html');await page.evaluate(async()=>{await (window as any).fontExample.ready;});});
test('real fonts, weights, italic, editable text and missing-font diagnostic appear in the inspector',async({page})=>{const state=await page.evaluate(()=>{const a=(window as any).fontExample.editor;return {catalog:a.getFonts(),issues:a.getFontIssues(),text:a.getDocument().nodes.find((n:any)=>n.id==='long-copy').text};});expect(state.catalog.find((f:any)=>f.id==='fraunces').variants).toHaveLength(4);expect(state.issues).toHaveLength(1);expect(state.issues[0].family).toBe('font-not-installed');await expect(page.locator('[data-node="headline"] > .node-text')).toHaveText(/Las palabras/);const styles=await page.evaluate(()=>{const canvas=(window as any).fontExample.view.getCanvasViewport();const title=getComputedStyle(canvas.querySelector('[data-node="headline"]')!),ital=getComputedStyle(canvas.querySelector('[data-node="italic"]')!);return {family:title.fontFamily,weight:title.fontWeight,italic:ital.fontStyle};});expect(styles.family).toContain('fraunces');expect(styles.weight).toBe('700');expect(styles.italic).toBe('italic');await page.getByRole('button',{name:'Fuente ausente',exact:true}).click();await expect(page.locator('#inspector').first()).toContainText('Fuente ausente: font-not-installed');await page.screenshot({path:'artifacts/typography-0.10.0/browser-missing.png',fullPage:true});});
test('inspector edits custom styles; undo, redo and reopen keep live text',async({page})=>{await page.locator('#title').click();await page.locator('#inspector select[data-field="fontStyle"]').selectOption('italic');await page.locator('#inspector select[data-field="fontWeight"]').selectOption('400');const values=await page.evaluate(()=>{const a=(window as any).fontExample.editor;const p=a.getDocument();a.undo();a.redo();a.importDocument(JSON.parse(JSON.stringify(p)));return a.getDocument().nodes.find((n:any)=>n.id==='headline');});expect(values.fontFamily).toBe('fraunces');expect(values.fontStyle).toBe('italic');expect(values.fontWeight).toBe(400);});
test('portable HTML and SVG keep text and fonts; missing references block exports',async({page})=>{const result=await page.evaluate(async()=>{const a=(window as any).fontExample.editor;let missing='';try{await a.exportSVGAsync('typography');}catch(e){missing=(e as Error).message;}a.apply([{op:'remove',ids:['missing-copy']}]);const html=await a.exportHTMLAsync(),svg=await a.exportSVGAsync('typography');return {missing,html,svg};});expect(result.missing).toContain('font-not-installed');expect(result.svg).toContain('<text');expect(result.svg).toContain('data:font/ttf;base64,');expect(result.html).toContain('@font-face');const preview=await page.context().newPage();await preview.setContent(result.html);await preview.evaluate(()=>document.fonts.ready);await expect(preview.locator('[data-node="headline"] > .node-text')).toHaveText(/Las palabras/);await preview.screenshot({path:'artifacts/typography-0.10.0/export-html.png',fullPage:true});await preview.close();await page.screenshot({path:'artifacts/typography-0.10.0/browser-fonts.png',fullPage:true});});
test('a failed real source is reported and cannot be exported or used by the agent',async({page})=>{const result=await page.evaluate(async()=>{const a=(window as any).fontExample.editor;a.registerFonts([{id:'broken',name:'Missing file',variants:[{weight:400,source:{url:'/no-such-font.woff2'}}]}]);await a.loadFonts(['broken']);const c=await a.agent('context');const response=await a.agent('apply',{expectedRevision:c.context.revision,operations:[{op:'update',id:'headline',patch:{fontFamily:'broken',fontWeight:400}}]});return {fonts:a.getFonts(),response};});expect(result.fonts.find((f:any)=>f.id==='broken').variants[0].status).toBe('error');expect(result.response.ok).toBe(false);});
test('browser SVG wrapping uses actual loaded-font widths and baseline; PNG export includes custom fonts',async({page})=>{const result=await page.evaluate(async()=>{const a=(window as any).fontExample.editor;a.apply([{op:'remove',ids:['missing-copy']}]);const svg=await a.exportSVGAsync('typography');const root=new DOMParser().parseFromString(svg,'image/svg+xml');const text=Array.from(root.querySelectorAll('text')).find(n=>n.textContent?.includes('La tipografía'))!;const lines=Array.from(text.querySelectorAll('tspan')).map(n=>n.textContent);const png=await a.exportAsset({ids:['long-copy'],format:'png',padding:0});return {lines,pngBytes:png.content.length,warnings:png.warnings};});expect(result.lines.length).toBeGreaterThan(3);expect(result.pngBytes).toBeGreaterThan(1000);});
test('modular view teardown and remount preserve edits while font faces are scoped to the view',async({page})=>{const r=await page.evaluate(async()=>{const {editor:a,view:v}=(window as any).fontExample;a.apply([{op:'update',id:'headline',patch:{text:'Humano: edición preservada'}}]);const faces=document.fonts.size;v.destroy();const p=a.getDocument();const {createEditorView}=await import(String('/src/modular.ts'));const next=createEditorView(a);next.mount('canvas',document.getElementById('canvas')!);await a.loadFonts();return {text:p.nodes.find((n:any)=>n.id==='headline').text,faces,before:document.fonts.size,issues:a.getFontIssues()};});expect(r.text).toContain('edición preservada');expect(r.before).toBe(r.faces);expect(r.issues).toHaveLength(1);});
test('a missing font on another screen does not block exporting this screen',async({page})=>{const r=await page.evaluate(async()=>{const a=(window as any).fontExample.editor;const p=a.getDocument();p.nodes.find((n:any)=>n.id==='missing-copy').parentId=null;a.importDocument(p);return a.exportSVGAsync('typography');});expect(r).toContain('Las palabras');});
test('raster export uses the actual loaded custom face, not a substituted system font',async({page})=>{const result=await page.evaluate(async()=>{const {editor:a,view:v}=(window as any).fontExample;a.apply([{op:'remove',ids:['missing-copy']}]);const svg=await a.exportAsset({ids:['headline'],format:'svg',padding:0}),png=await a.exportAsset({ids:['headline'],format:'png',padding:0});const root=new DOMParser().parseFromString(svg.content,'image/svg+xml'),text=root.querySelector('text')!;const actual=document.createElement('canvas'),expected=document.createElement('canvas');actual.width=expected.width=Math.round(png.width);actual.height=expected.height=Math.round(png.height);const image=new Image();image.src='data:image/png;base64,'+png.content;await image.decode();const ca=actual.getContext('2d')!,ce=expected.getContext('2d')!;ca.drawImage(image,0,0);const style=getComputedStyle(v.getCanvasViewport().querySelector('[data-node="headline"]'));ce.font=`${style.fontStyle} ${style.fontWeight} ${style.fontSize} ${style.fontFamily}`;ce.fillStyle=style.color;for(const line of text.querySelectorAll('tspan'))ce.fillText(line.textContent!,Number(line.getAttribute('x')),Number(line.getAttribute('y')));const aa=ca.getImageData(0,0,actual.width,actual.height).data,bb=ce.getImageData(0,0,actual.width,actual.height).data;let differing=0,ink=0;for(let i=3;i<aa.length;i+=4){if(aa[i]>20||bb[i]>20){ink++;if(Math.abs(aa[i]-bb[i])>60)differing++;}}return {difference:differing/ink,png:png.content};});expect(result.difference).toBeLessThan(.08);const fs=await import('node:fs/promises');await fs.writeFile('artifacts/typography-0.10.0/export-headline.png',Buffer.from(result.png,'base64'));});

test('inspector lists only declared variants and preserves missing family selection',async({page})=>{await page.locator('#title').click();await expect(page.locator('#inspector select[data-field="fontWeight"] option')).toHaveText(['400','700']);await expect(page.locator('#inspector select[data-field="fontStyle"] option')).toHaveText(['Normal','Cursiva']);await page.locator('#missing').click();await expect(page.locator('#inspector select[data-field="fontFamily"]')).toHaveValue('font-not-installed');});
test('font completion during a human edit keeps the edit and refreshes after blur',async({page})=>{const text=page.locator('#inspector textarea[data-field="text"]');await text.fill('Humano: trabajo sin perder');await page.evaluate(async()=>{const {editor:a,fonts}=(window as any).fontExample;const r=(await import(String('/src/editor-core.ts'))).getEditorSession(a).fonts;r.set(fonts);await a.loadFonts();});await text.press('Tab');await page.locator('#fit').click();await expect(page.locator('[data-node="headline"] > .node-text')).toHaveText('Humano: trabajo sin perder');const result=await page.evaluate(()=>{const a=(window as any).fontExample.editor;return {text:a.getDocument().nodes.find((n:any)=>n.id==='headline').text,issues:a.getFontIssues()};});expect(result.text).toBe('Humano: trabajo sin perder');expect(result.issues).toHaveLength(1);});

test('generic SVG exports remain available in a browser core without a mounted view or font loader',async({page})=>{const svg=await page.evaluate(async()=>{const {createEditor}=await import(String('/src/editor-core.ts'));const p=(window as any).fontExample.editor.getDocument();for(const n of p.nodes){n.fontFamily='system';delete n.typographyToken;}const a=createEditor({document:p});try{return await a.exportSVGAsync('typography');}finally{a.destroy();}});expect(svg).toContain('<text');expect(svg).toContain('Las palabras');});
test('declared weights produce distinct real glyph widths rather than descriptor-only differences',async({page})=>{const widths=await page.evaluate(()=>{const v=(window as any).fontExample.view,source=v.getCanvasViewport().querySelector('[data-node="headline"]'),family=getComputedStyle(source).fontFamily;return [400,700].map(weight=>{const span=document.createElement('span');Object.assign(span.style,{position:'absolute',fontFamily:family,fontWeight:String(weight),fontSize:'62px',fontOpticalSizing:'none',fontSynthesis:'none',whiteSpace:'pre'});span.textContent='Las palabras construyen lugares.';document.body.append(span);const w=span.getBoundingClientRect().width;span.remove();return w;});});expect(Math.abs(widths[0]-widths[1])).toBeGreaterThan(15);});

test('the design system reports missing typography tokens without crashing or showing substitutes',async({page})=>{const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));await page.evaluate(()=>{const {editor:a,view:v}=(window as any).fontExample,p=a.getDocument();p.designThemes.project.modes.light.typography.absent={name:'Missing token',fontFamily:'not-installed-token',fontWeight:400,fontSize:24,lineHeight:1.3};a.importDocument(p);const menu=document.createElement('aside');document.body.append(menu);v.mount('system',menu);const modes=document.createElement('aside');document.body.append(modes);v.mount('modes',modes);});await page.locator('[data-mode="system"]').click();await page.locator('[data-system-page="tipografia"]').first().click();await expect(page.getByRole('alert').filter({hasText:'Fuente ausente: not-installed-token'})).toBeVisible();expect(errors).toEqual([]);});

test('iframe fonts resolve relative URLs from the host for initial, replacement and added catalogs',async({page})=>{
 const result=await page.evaluate(async()=>{
  const {mountCodaru}=await import(String('/src/embed.ts'));
  const container=document.createElement('div');document.body.append(container);
  const font=(id:string,file:string)=>({id,name:id,variants:[{weight:400,source:{url:'./font-assets/'+file},export:'embed' as const}]});
  const handle=mountCodaru(container,{editorUrl:'/index.html',nativeAgent:false,fonts:[font('relative','fraunces-regular.ttf')]});
  try{
   const api=await handle.ready;await api.loadFonts(['relative']);const initial=api.getFonts().find((f:import('../../src/contracts').FontSummary)=>f.id==='relative')!.variants[0].status;
   api.setFonts([font('replacement','spacegrotesk-regular.ttf')]);await api.loadFonts(['replacement']);const replacement=api.getFonts().find((f:import('../../src/contracts').FontSummary)=>f.id==='replacement')!.variants[0].status;
   api.registerFonts([font('added','fraunces-italic.ttf')]);await api.loadFonts(['added']);const added=api.getFonts().find((f:import('../../src/contracts').FontSummary)=>f.id==='added')!.variants[0].status;
   return {initial,replacement,added};
  }finally{await handle.destroy();container.remove();}
 });
 expect(result).toEqual({initial:'loaded',replacement:'loaded',added:'loaded'});
});
