import { createEditor, createEditorView, type CodaruInvoke } from '../src/modular';
import { propertiesDesign } from './properties-design';
const fixture = propertiesDesign();
const editor = createEditor({ document: fixture.document });
const native = (window as unknown as { __TAURI_INTERNALS__?: { invoke: CodaruInvoke } }).__TAURI_INTERNALS__;
const view = createEditorView(editor, { appearance: { theme: 'light' }, invoke: native?.invoke.bind(native), nativeAgent: !!native });
const el = (id: string) => document.getElementById(id)!;
for (const part of ['canvas', 'layers', 'inspector', 'library', 'toolbar', 'dialogs'] as const) view.mount(part, el(`${part}-slot`));
el('change-master').onclick = () => { const current = editor.getDocument().nodes.find(n => n.id === 'button')!; editor.apply([{ op: 'update', id: 'button', patch: { fill: current.fill === '#7255db' ? '#177c68' : '#7255db' } }]); };
el('select-local').onclick = () => editor.select([fixture.ids.second]);
el('undo').onclick = () => editor.undo(); el('fit').onclick = () => view.fit();
const title = el('host-title') as HTMLInputElement, description = el('host-description') as HTMLInputElement;
const edit = (key: string, value: string | boolean) => { title.blur(); description.blur(); try { editor.setComponentProperty(fixture.ids.second,key,value); el('host-error').textContent=''; } catch(error) { el('host-error').textContent=String(error); } };
title.onchange=()=>edit('titulo',title.value); description.onchange=()=>edit('descripcion',description.checked);
editor.subscribe(state => { const props=editor.getComponentProperties(fixture.ids.second); title.value=String(props.find(p=>p.key==='titulo')!.value); description.checked=props.find(p=>p.key==='descripcion')!.value===true; });
editor.subscribe(state => { (el('undo') as HTMLButtonElement).disabled = !state.canUndo; el('status').textContent = `${state.document.components.length} componentes · ${state.document.nodes.length} capas · Propiedades públicas · Historial compartido con el IDE`; });
editor.select([fixture.ids.second]); view.fit();
Object.assign(window, { propertiesExample: { editor, view, ids: fixture.ids } });
window.addEventListener('pagehide', () => editor.destroy(), { once: true });
