import {getEditorSession,type CodaruEditor} from './editor-core';
import {captureCommentAnchor,commentBounds,emptyComments,getCommentContext} from './comments';
import type {CommentAuthor,CommentDraft,CommentOperation,CommentReviewRequest} from './contracts';
import {applyAppearance,type EditorAppearance} from './ui-theme';
import chrome from './chrome-style.css?inline';
import css from './comments-view.css?inline';
export type {CommentAnchor,CommentContext,CommentEvent,CommentThread,CommentReviewRequest} from './contracts';
export interface CommentsViewOptions {appearance?:EditorAppearance;ownerDocument?:Document;styleNonce?:string;author?:CommentAuthor;onError?:(error:Error)=>void;onOpen?:(id:string)=>void;onReveal?:(ids:string[])=>void|Promise<void>;onAIRequest?:(request:CommentReviewRequest)=>void|Promise<void>;}
export interface CommentsFragment {element:HTMLElement;setAppearance(value:EditorAppearance):void;destroy():void;}
export interface CommentsView {mountPanel(container:HTMLElement):CommentsFragment;/** Container must be the actual canvas viewport (same origin as pan). */mountPins(viewport:HTMLElement):CommentsFragment;open(id:string):void;setAppearance(value:EditorAppearance):void;flush():void;destroy():void;}
const esc=(v:unknown)=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]!));
const uid=()=>`comment-${crypto.randomUUID()}`;
/** Optional panel and pins: one session, no global listeners, no model or storage engine. */
export function createCommentsView(editor:CodaruEditor,options:CommentsViewOptions={}):CommentsView{
 const session=getEditorSession(editor),owner=options.ownerDocument??document,author=options.author??{name:'Usuario',kind:'human' as const};
 let appearance=options.appearance??{},disposed=false,panel:HTMLElement|undefined,pins:HTMLElement|undefined,selected='',error='',filter='open',draft:CommentDraft|undefined,dirty=false,working=false,flushing=false,lastProject=session.store.project,lastSelection='',cache=editor.getComments();
 const handles=new Set<CommentsFragment>();
 const pinNodes=new Map<string,HTMLButtonElement>();
 draft=cache.drafts[0];if(draft?.threadId)selected=draft.threadId;
 function assert(){if(disposed)throw new Error('El panel de comentarios fue desmontado.');session.assertActive();}
 function report(e:unknown){error=e instanceof Error?e.message:String(e);options.onError?.(new Error(error));const alert=panel?.querySelector('[role=alert]');if(alert)alert.textContent=error;}
 function flush(){if(!dirty||!draft)return;const saved=draft;dirty=false;flushing=true;try{editor.apply([{op:'comment.draft.put',draft:saved}]);}catch(e){dirty=true;throw e;}finally{flushing=false;}}
 function data(){return session.store.project.comments??emptyComments();}
 function selectionLabel(){const p=session.store.project;return session.state.selected.map(id=>p.nodes.find(n=>n.id===id)?.name??id).join(' · ')||'Selecciona un elemento del layout';}
 function draftLabel(){return draft?draft.anchor.labels.join(' · '):selectionLabel();}
 function refreshPins(){if(!pins)return;const p=session.store.project,list=data().threads.filter(t=>t.status==='open'&&p.nodes.some(n=>n.id===t.anchor.frameId&&n.parentId===null&&(n.page??p.pages?.[0]?.id)===(p.activePageId??p.pages?.[0]?.id)));
  const ids=new Set(list.map(t=>t.id));for(const [id,b] of pinNodes)if(!ids.has(id)){b.remove();pinNodes.delete(id);}
  list.forEach((t,i)=>{let b=pinNodes.get(t.id);if(!b){b=owner.createElement('button');b.dataset.thread=t.id;b.className='pin';pins!.append(b);pinNodes.set(t.id,b);}const box=commentBounds(p,t.anchor),pos={x:box.x+box.width,y:box.y};b.textContent=String(i+1);b.title=t.messages[0].text.slice(0,200);b.setAttribute('aria-label',`Comentario ${i+1}: ${t.anchor.labels.join(', ')}`);b.setAttribute('aria-pressed',String(t.id===selected));b.style.left=`${session.state.pan.x+pos.x*session.state.zoom}px`;b.style.top=`${session.state.pan.y+pos.y*session.state.zoom}px`;});
 }
 function renderPanel(){if(!panel)return;const focused=panel.getRootNode() as ShadowRoot;if(dirty||focused.activeElement?.matches('textarea,input')){const label=panel.querySelector('[data-selection]');if(label)label.textContent=draftLabel();return;}
  const d=data(),thread=d.threads.find(t=>t.id===selected),context=thread?getCommentContext(session.store.project,thread.id):null;
  panel.innerHTML=`<header><span class="eyebrow">REVISIÓN DEL LAYOUT</span><h2>Comentarios <span class="badge">${d.threads.filter(t=>t.status==='open').length}</span></h2></header><p role="alert" class="error">${esc(error)}</p><div class="actions"><button data-new>Comentar selección</button><label class="filter">Mostrar<select data-filter><option value="open" ${filter==='open'?'selected':''}>Abiertos</option><option value="all" ${filter==='all'?'selected':''}>Todos</option><option value="resolved" ${filter==='resolved'?'selected':''}>Resueltos</option></select></label></div><div class="thread-list">${d.threads.filter(t=>filter==='all'||t.status===filter).map((t,i)=>`<button class="thread-row" data-thread="${esc(t.id)}" aria-pressed="${t.id===selected}"><span class="badge">${i+1}</span><span><strong>${esc(t.anchor.labels.join(' · '))}</strong><span class="preview">${esc(t.messages[0].text.slice(0,100))}</span></span></button>`).join('')||'<p class="muted">Sin comentarios en esta vista.</p>'}</div>${thread?`<article><div class="actions"><strong>${esc(thread.anchor.labels.join(' · '))}</strong><span class="badge">${thread.status==='open'?'Abierto':'Resuelto'}</span><button data-reveal>Mostrar elemento</button></div><p class="muted">${esc(thread.anchor.theme.id)} · ${thread.anchor.theme.mode==='dark'?'Oscuro':'Claro'}</p>${context?.missingIds.length?'<p class="warning">Una capa se eliminó o cambió de pantalla. El hilo conserva su ancla original.</p>':''}${context?.stale?'<p class="warning">El layout cambió desde el comentario. La IA debe revisar el contexto actual.</p>':''}${thread.messages.map(m=>`<section class="message"><div class="item-head"><strong>${esc(m.author.name)}${m.author.kind==='ai'?' · IA':''}</strong><time>${esc(new Date(m.at).toLocaleString('es'))}</time></div><p>${esc(m.text)}</p></section>`).join('')}<div class="actions"><button data-status="${thread.status==='open'?'resolved':'open'}">${thread.status==='open'?'Resolver':'Reabrir'}</button><button data-ai ${working||!options.onAIRequest?'disabled':''}>${working?'Esperando al IDE…':'Pedir propuesta a la IA'}</button></div></article>`:''}<form><p data-selection class="muted">${esc(draftLabel())}</p><label>${thread?'Responder':'Nuevo comentario'}<textarea aria-label="Texto del comentario" maxlength="4000" rows="4" ${thread?.status==='resolved'?'disabled':''}>${esc(draft?.text??'')}</textarea></label><p class="hint">El borrador se conserva al cerrar. Sólo Publicar envía el evento al IDE.</p><div class="actions"><button type="submit" ${thread?.status==='resolved'?'disabled':''}>Publicar</button><button type="button" data-discard>Descartar borrador</button>${draft?'<button type="button" data-anchor>Actualizar ancla</button>':''}</div></form>${d.drafts.filter(v=>v.id!==draft?.id).map(v=>`<button data-draft="${esc(v.id)}">Retomar: ${esc(v.text.slice(0,80))}</button>`).join('')}`;
 }
 function invalidate(){if(disposed)return;const changed=lastProject!==session.store.project;if(changed){lastProject=session.store.project;cache=data();if(!dirty&&!flushing){if(draft&&!cache.drafts.some(d=>d.id===draft!.id))draft=undefined;if(selected&&!cache.threads.some(t=>t.id===selected))selected='';renderPanel();}}const sig=session.state.selected.join('|');if(sig!==lastSelection){lastSelection=sig;const label=panel?.querySelector('[data-selection]');if(label)label.textContent=draftLabel();}refreshPins();}
 async function reveal(id:string){const t=data().threads.find(t=>t.id===id);if(!t)return;const p=session.store.project,frame=p.nodes.find(n=>n.id===t.anchor.frameId);if(frame?.page&&frame.page!==p.activePageId)editor.commit(p=>{p.activePageId=frame.page;});const ids=t.anchor.nodeIds.filter(id=>p.nodes.some(n=>n.id===id));editor.select(ids);await options.onReveal?.(ids);}
 function open(id:string){flush();selected=id;options.onOpen?.(id);draft=data().drafts.find(d=>d.threadId===id);renderPanel();refreshPins();}
 async function click(e:Event){e.stopPropagation();const b=(e.target as HTMLElement).closest<HTMLElement>('button');if(!b)return;try{if(b.dataset.thread){open(b.dataset.thread);await reveal(b.dataset.thread);return;}if(b.hasAttribute('data-new')){flush();selected='';draft=undefined;error='';renderPanel();return;}if(b.dataset.draft){flush();draft=data().drafts.find(d=>d.id===b.dataset.draft);selected=draft?.threadId??'';renderPanel();return;}if(b.hasAttribute('data-discard')){dirty=false;if(draft&&data().drafts.some(d=>d.id===draft!.id))editor.apply([{op:'comment.draft.remove',id:draft.id}]);draft=undefined;error='';renderPanel();return;}if(b.hasAttribute('data-anchor')&&draft){draft={...draft,anchor:editor.captureCommentAnchor(draft.anchor.nodeIds)};dirty=true;flush();error='';renderPanel();return;}if(b.hasAttribute('data-reveal')){flush();await reveal(selected);}if(b.dataset.status){flush();editor.apply([{op:'comment.status',id:selected,status:b.dataset.status as 'open'|'resolved'}]);}if(b.hasAttribute('data-ai')&&options.onAIRequest){flush();const context=editor.getCommentContext(selected);if(context.missingIds.length||!context.currentRevision)throw new Error('El ancla debe existir para pedir un ajuste.');working=true;renderPanel();try{await options.onAIRequest({context,document:editor.getDocument()});}finally{working=false;if(!disposed)renderPanel();}}}catch(e){report(e);}}
 function input(e:Event){if(!(e.target instanceof owner.defaultView!.HTMLTextAreaElement))return;try{const t=data().threads.find(t=>t.id===selected);if(!draft)draft={id:uid(),...(t?{threadId:t.id}:{}),anchor:t?.anchor??editor.captureCommentAnchor(),text:e.target.value,author};else draft={...draft,text:e.target.value};dirty=true;}catch(e){report(e);}}
 function blur(){try{if(draft&&!draft.text.trim()){dirty=false;if(data().drafts.some(d=>d.id===draft!.id))editor.apply([{op:'comment.draft.remove',id:draft.id}]);draft=undefined;}else flush();}catch(e){report(e);}}
 function submit(e:Event){e.preventDefault();try{const text=panel?.querySelector<HTMLTextAreaElement>('textarea')?.value.trim();if(!text)throw new Error('Escribe un comentario antes de publicar.');if(!draft)throw new Error('Selecciona el elemento que quieres comentar.');const d=draft,message={id:uid(),text,author:d.author,at:new Date().toISOString()},ops:CommentOperation[]=[];if(data().drafts.some(v=>v.id===d.id))ops.push({op:'comment.draft.remove',id:d.id});const id=d.threadId??uid();ops.push(d.threadId?{op:'comment.reply',id,message}:{op:'comment.create',id,anchor:d.anchor,message});dirty=false;try{editor.apply(ops);}catch(e){dirty=true;throw e;}draft=undefined;selected=id;error='';renderPanel();refreshPins();}catch(e){report(e);}}
 const unbind=session.bindExtension({flush,dispose:destroy,isBusy:()=>dirty,notify:invalidate});
 function mount(container:HTMLElement,kind:'panel'|'pins'):CommentsFragment{assert();if(container.ownerDocument!==owner)throw new Error('Los fragmentos deben compartir documento.');if(kind==='panel'?panel:pins)throw new Error('Este fragmento ya está montado.');const host=owner.createElement('div');host.dataset.codaruComments=kind;applyAppearance(host,appearance);host.style.cssText=kind==='pins'?'position:absolute;inset:0;overflow:hidden;pointer-events:none;z-index:30;':'height:100%;min-height:0;';const shadow=host.attachShadow({mode:'open'}),style=owner.createElement('style');style.textContent=chrome+'\n'+css;const nonce=options.styleNonce??Array.from(owner.querySelectorAll('style')).find(s=>s.nonce)?.nonce;if(nonce)style.nonce=nonce;const root=owner.createElement('div');root.className=kind==='panel'?'comments-panel':'comments-pins';shadow.append(style,root);container.append(host);if(kind==='panel'){panel=root;root.addEventListener('input',input);root.addEventListener('focusout',blur);root.addEventListener('submit',submit);root.addEventListener('change',e=>{const el=e.target as HTMLSelectElement;if(el.hasAttribute('data-filter')){filter=el.value;renderPanel();}});}else{pins=root;root.addEventListener('pointerdown',e=>e.stopPropagation());root.addEventListener('dblclick',e=>e.stopPropagation());}root.addEventListener('click',click);renderPanel();refreshPins();let removed=false;const handle:CommentsFragment={element:host,setAppearance:value=>applyAppearance(host,value),destroy(){if(removed)return;flush();removed=true;if(kind==='panel'){panel=undefined;}else{pins=undefined;pinNodes.clear();}host.remove();handles.delete(handle);}};handles.add(handle);return handle;}
 function destroy(){if(disposed)return;flush();for(const h of [...handles])h.destroy();disposed=true;unbind();}
 return {mountPanel:c=>mount(c,'panel'),mountPins:c=>mount(c,'pins'),open,setAppearance(value){assert();appearance={...appearance,...value,tokens:{...appearance.tokens,...value.tokens}};for(const h of handles)h.setAppearance(value);},flush,destroy};
}
