import type { FontLoader, FontDefinition, FontVariant } from './contracts';
/** One loader per view/realm. Never registers fonts under host CSS family names. */
export function createBrowserFontLoader(owner:Document):FontLoader{
 const faces=new Set<FontFace>();let epoch=0;
 const source=(v:FontVariant)=>'url' in v.source?`url(${JSON.stringify(new URL(v.source.url,owner.baseURI).href)})`:`local(${JSON.stringify(v.source.local)})`;
 return {
 async load(family,v){const current=epoch,ctor=(owner.defaultView as unknown as {FontFace:typeof FontFace}).FontFace;const face=new ctor(family.replace(/^"|"$/g,''),source(v),{weight:String(v.weight),style:v.style??'normal'});await Promise.race([face.load(),new Promise<never>((_,reject)=>{const t=setTimeout(()=>reject(new Error('Tiempo de carga de fuente excedido (15 s).')),15000);face.loaded.finally(()=>clearTimeout(t)).catch(()=>{});})]);if(epoch!==current)return;owner.fonts.add(face);faces.add(face);await Promise.resolve();},
 measure(text,font){const probe=owner.createElement('span');Object.assign(probe.style,{position:'absolute',left:'-99999px',top:'0',whiteSpace:'pre',visibility:'hidden',fontFamily:font.family,fontWeight:String(font.weight),fontStyle:font.style??'normal',fontSize:`${font.size}px`,fontSynthesis:'none',fontOpticalSizing:'none'});probe.textContent=text;owner.body.append(probe);try{return probe.getBoundingClientRect().width;}finally{probe.remove();}},
 baseline(font,lineHeight){const probe=owner.createElement('span'),marker=owner.createElement('i');Object.assign(probe.style,{position:'absolute',left:'-99999px',whiteSpace:'pre',fontFamily:font.family,fontSize:`${font.size}px`,fontWeight:String(font.weight),fontStyle:font.style??'normal',lineHeight:String(lineHeight),fontSynthesis:'none',fontOpticalSizing:'none'});probe.textContent='Hg';Object.assign(marker.style,{display:'inline-block',width:'0',height:'0',verticalAlign:'baseline'});probe.append(marker);owner.body.append(probe);try{return marker.getBoundingClientRect().top-probe.getBoundingClientRect().top;}finally{probe.remove();}},
 async css(ds:FontDefinition[]){let total=0;const cache=new Map<string,string>();const rules:string[]=[];for(const d of ds)for(const v of d.variants){if(!('url' in v.source))throw new Error('La fuente local no entrega bytes.');const url=new URL(v.source.url,owner.baseURI).href;let data=cache.get(url);if(!data){const controller=new AbortController(),timer=setTimeout(()=>controller.abort(),15000);let response:Response;try{response=await fetch(url,{signal:controller.signal,credentials:'same-origin'});if(!response.ok)throw new Error(`Fuente HTTP ${response.status}`);const buffer=await response.arrayBuffer();total+=buffer.byteLength;if(total>8_000_000)throw new Error('Los archivos de fuentes superan 8 MB.');const bytes=new Uint8Array(buffer);let binary='';for(let i=0;i<bytes.length;i+=8192)binary+=String.fromCharCode(...bytes.subarray(i,i+8192));const signature=String.fromCharCode(...bytes.subarray(0,4));const mime=signature==='wOF2'?'font/woff2':signature==='wOFF'?'font/woff':signature==='OTTO'?'font/otf':'font/ttf';data=`data:${mime};base64,${btoa(binary)}`;cache.set(url,data);}finally{clearTimeout(timer);}}rules.push(`@font-face{font-family:${d.id};font-weight:${v.weight};font-style:${v.style??'normal'};src:url("${data}");font-display:block;}`);}return rules.join('');},
 dispose(){epoch++;for(const face of faces)owner.fonts.delete(face);faces.clear();}
 };
}
