import type { Project } from './model';
import type { IdentityLab, IdentityBrief, IdentityOperation, IdentityDirection, IdentityEvidence, IdentityIssue, IdentityPackage } from './contracts';

const copy = <T>(value:T):T => JSON.parse(JSON.stringify(value));
const ID=/^[A-Za-z0-9][A-Za-z0-9_-]{0,127}$/;
const REV=/^[a-f0-9]{64}$/;
function record(value:unknown,label:string):Record<string,unknown>{if(!value||typeof value!=='object'||Array.isArray(value))throw new Error(`${label}: se esperaba un objeto.`);return value as Record<string,unknown>;}
function text(value:unknown,label:string,max=4000,required=false){if(typeof value!=='string'||value.length>max||(required&&!value.trim())||/[\u0000-\u0008\u000b\u000c\u000e-\u001f]/.test(value))throw new Error(`${label}: texto inválido (máximo ${max}).`);}
function id(value:unknown,label:string){text(value,label,128,true);if(!ID.test(value as string)||['constructor','prototype','__proto__'].includes(value as string))throw new Error(`${label}: identificador inválido.`);}
function choice(value:unknown,values:string[],label:string){if(!values.includes(value as string))throw new Error(`${label}: valor inválido.`);}
function list(value:unknown,label:string,max:number,check:(value:unknown,label:string)=>void){if(!Array.isArray(value)||value.length>max)throw new Error(`${label}: lista inválida (máximo ${max}).`);value.forEach((v,i)=>check(v,`${label}[${i}]`));}
function ids(value:unknown,label:string,max=100){list(value,label,max,id);if(new Set(value as string[]).size!==(value as string[]).length)throw new Error(`${label}: IDs repetidos.`);}
function keys(value:Record<string,unknown>,allowed:string[],label:string){for(const key of Object.keys(value))if(!allowed.includes(key))throw new Error(`${label}.${key}: campo desconocido.`);}
export function emptyIdentityLab():IdentityLab{return {format:'codaru-identity/1',brief:{intent:'',audience:'',context:'',qualities:[],avoid:[],constraints:[]},references:[],directions:[],critiques:[],decisions:[],refinements:[]};}
export function validateIdentityBrief(input:unknown):asserts input is IdentityBrief{
  const b=record(input,'brief');keys(b,['intent','audience','context','qualities','avoid','constraints'],'brief');
  for(const k of ['intent','audience','context'])text(b[k],`brief.${k}`);
  for(const k of ['qualities','avoid','constraints'])list(b[k],`brief.${k}`,40,(v,l)=>text(v,l,1000,true));
}
function reference(input:unknown,label:string){const r=record(input,label);keys(r,['id','title','source','author','community','license','kind','observations','interpretation','status'],label);id(r.id,`${label}.id`);text(r.title,`${label}.title`,160,true);text(r.source,`${label}.source`,2000,true);if(/^(javascript|data|vbscript):/i.test((r.source as string).trim()))throw new Error('La procedencia no permite URLs ejecutables.');for(const key of ['author','community','license','interpretation'])if(r[key]!==undefined)text(r[key],`${label}.${key}`,2000);text(r.observations,`${label}.observations`);choice(r.kind,['cultural','visual','material','other'],label);choice(r.status,['proposed','accepted'],label);}
function direction(input:unknown,label:string){const d=record(input,label);keys(d,['id','name','intent','frameIds','styleIds','referenceIds','status','proposal'],label);id(d.id,`${label}.id`);text(d.name,`${label}.name`,160,true);text(d.intent,`${label}.intent`);ids(d.frameIds,`${label}.frameIds`,12);ids(d.styleIds,`${label}.styleIds`,30);if(d.referenceIds!==undefined)ids(d.referenceIds,`${label}.referenceIds`);choice(d.status,['exploring','selected','archived'],label);if(d.proposal!==undefined)text(d.proposal,`${label}.proposal`,12000);}
function evidence(input:unknown,label:string){const e=record(input,label);keys(e,['revision','frameId','dataURL','width','height'],label);id(e.frameId,`${label}.frameId`);if(!REV.test(String(e.revision)))throw new Error('Evidencia requiere revisión exacta.');if(typeof e.dataURL!=='string'||e.dataURL.length>2_000_000||!/^data:image\/png;base64,iVBORw0KGgo[A-Za-z0-9+/]*={0,2}$/.test(e.dataURL))throw new Error('Evidencia requiere un render PNG local, hasta 2 MB.');for(const k of ['width','height'])if(!Number.isInteger(e[k])||(e[k] as number)<1||(e[k] as number)>8192)throw new Error('Dimensión de evidencia inválida.');
  let binary:string;try{binary=atob((e.dataURL as string).split(',')[1]);}catch{throw new Error('PNG de evidencia inválido.');}
  const bytes=Uint8Array.from(binary,c=>c.charCodeAt(0)),view=new DataView(bytes.buffer);if(bytes.length<57||view.getUint32(8)!==13||String.fromCharCode(...bytes.slice(12,16))!=='IHDR'||view.getUint32(16)!==e.width||view.getUint32(20)!==e.height)throw new Error('Las dimensiones deben corresponder al PNG real.');
  let offset=8,hasData=false,ended=false;while(offset+12<=bytes.length){const size=view.getUint32(offset),end=offset+size+12;if(end>bytes.length)throw new Error('PNG truncado.');const tag=String.fromCharCode(...bytes.slice(offset+4,offset+8));if(tag==='IDAT'&&size>0)hasData=true;if(tag==='IEND'){if(size!==0||end!==bytes.length)throw new Error('PNG inválido.');ended=true;break;}offset=end;}if(!hasData||!ended)throw new Error('PNG sin datos de imagen.');
}
function critique(input:unknown,label:string){const c=record(input,label);keys(c,['id','directionId','targetRevision','summary','findings','evaluator','evidence'],label);id(c.id,`${label}.id`);id(c.directionId,`${label}.directionId`);if(!REV.test(String(c.targetRevision)))throw new Error('Crítica requiere revisión exacta.');text(c.summary,`${label}.summary`,4000,true);const evaluator=record(c.evaluator,'evaluator');keys(evaluator,['provider','model'],'evaluator');text(evaluator.provider,'provider',160,true);text(evaluator.model,'model',160,true);list(c.findings,`${label}.findings`,40,(v,l)=>{const f=record(v,l);keys(f,['criterion','assessment','reason','nodeIds'],l);text(f.criterion,'criterion',200,true);text(f.reason,'reason',2000,true);choice(f.assessment,['pass','needs_work'],'assessment');ids(f.nodeIds,'nodeIds',100);});list(c.evidence,`${label}.evidence`,12,evidence);if(!(c.evidence as unknown[]).length)throw new Error('La crítica visual requiere renders reales.');const renders=c.evidence as IdentityEvidence[];if(renders.some(e=>e.revision!==c.targetRevision)||new Set(renders.map(e=>e.frameId)).size!==renders.length)throw new Error('La evidencia debe corresponder a una única revisión exacta.');}
function decision(input:unknown,label:string){const d=record(input,label);keys(d,['id','directionId','criterion','observation','next','outcome','author','at'],label);id(d.id,`${label}.id`);if(d.directionId!==undefined)id(d.directionId,'directionId');text(d.criterion,'criterion',200,true);text(d.observation,'observation',4000,true);text(d.next,'next');text(d.author,'author',160,true);text(d.at,'at',40,true);if(!/^\d{4}-\d\d-\d\dT/.test(d.at as string)||!Number.isFinite(Date.parse(d.at as string)))throw new Error('Fecha de decisión inválida.');choice(d.outcome,['keep','revise','discard'],'outcome');}
function refinement(input:unknown,label:string){const r=record(input,label);keys(r,['id','directionId','nodeIds','instruction','targetRevision','proposal','status'],label);id(r.id,`${label}.id`);id(r.directionId,'directionId');ids(r.nodeIds,'nodeIds');if(!(r.nodeIds as string[]).length)throw new Error('Refinamiento requiere una selección.');text(r.instruction,'instruction',4000,true);if(!REV.test(String(r.targetRevision)))throw new Error('Refinamiento requiere revisión exacta.');if(r.proposal!==undefined)text(r.proposal,'proposal',12000,true);choice(r.status,['requested','proposed','resolved'],'status');if(r.status==='proposed'&&r.proposal===undefined)throw new Error('Falta propuesta de refinamiento.');}
export function validateIdentityLab(input:unknown):asserts input is IdentityLab{
  const l=record(input,'identityLab');keys(l,['format','brief','references','directions','critiques','decisions','refinements'],'identityLab');if(l.format!=='codaru-identity/1')throw new Error('Versión de Identity Lab inválida.');validateIdentityBrief(l.brief);
  for(const [key,max,check] of [['references',100,reference],['directions',30,direction],['critiques',30,critique],['decisions',200,decision],['refinements',100,refinement]] as const){list(l[key],key,max,check);const all=l[key] as {id:string}[];if(new Set(all.map(v=>v.id)).size!==all.length)throw new Error(`${key}: IDs repetidos.`);}
  const rasterBytes=(l.critiques as IdentityLab['critiques']).reduce((s,c)=>s+c.evidence.reduce((n,e)=>n+e.dataURL.length,0),0);if(rasterBytes>12_000_000)throw new Error('Máximo 12 MB de evidencia visual por laboratorio.');
}

/** Dependency-free SHA-256 keeps review state synchronous in DOM-free snapshots. */
export function identityHash(value:string):string {
  const bytes=new TextEncoder().encode(value),length=bytes.length,buffer=new Uint8Array(Math.ceil((length+9)/64)*64);buffer.set(bytes);buffer[length]=128;const view=new DataView(buffer.buffer);view.setUint32(buffer.length-8,Math.floor(length/0x20000000));view.setUint32(buffer.length-4,(length*8)>>>0);
  const k=[0x428a2f98,0x71374491,0xb5c0fbcf,0xe9b5dba5,0x3956c25b,0x59f111f1,0x923f82a4,0xab1c5ed5,0xd807aa98,0x12835b01,0x243185be,0x550c7dc3,0x72be5d74,0x80deb1fe,0x9bdc06a7,0xc19bf174,0xe49b69c1,0xefbe4786,0x0fc19dc6,0x240ca1cc,0x2de92c6f,0x4a7484aa,0x5cb0a9dc,0x76f988da,0x983e5152,0xa831c66d,0xb00327c8,0xbf597fc7,0xc6e00bf3,0xd5a79147,0x06ca6351,0x14292967,0x27b70a85,0x2e1b2138,0x4d2c6dfc,0x53380d13,0x650a7354,0x766a0abb,0x81c2c92e,0x92722c85,0xa2bfe8a1,0xa81a664b,0xc24b8b70,0xc76c51a3,0xd192e819,0xd6990624,0xf40e3585,0x106aa070,0x19a4c116,0x1e376c08,0x2748774c,0x34b0bcb5,0x391c0cb3,0x4ed8aa4a,0x5b9cca4f,0x682e6ff3,0x748f82ee,0x78a5636f,0x84c87814,0x8cc70208,0x90befffa,0xa4506ceb,0xbef9a3f7,0xc67178f2];
  const h=[0x6a09e667,0xbb67ae85,0x3c6ef372,0xa54ff53a,0x510e527f,0x9b05688c,0x1f83d9ab,0x5be0cd19],w=new Uint32Array(64),rotr=(x:number,n:number)=>(x>>>n)|(x<<(32-n));
  for(let offset=0;offset<buffer.length;offset+=64){for(let i=0;i<16;i++)w[i]=view.getUint32(offset+i*4);for(let i=16;i<64;i++){const a=w[i-15],b=w[i-2];w[i]=(w[i-16]+(rotr(a,7)^rotr(a,18)^(a>>>3))+w[i-7]+(rotr(b,17)^rotr(b,19)^(b>>>10)))>>>0;}let [a,b,c,d,e,f,g,z]=h;for(let i=0;i<64;i++){const t1=(z+(rotr(e,6)^rotr(e,11)^rotr(e,25))+((e&f)^(~e&g))+k[i]+w[i])>>>0,t2=((rotr(a,2)^rotr(a,13)^rotr(a,22))+((a&b)^(a&c)^(b&c)))>>>0;z=g;g=f;f=e;e=(d+t1)>>>0;d=c;c=b;b=a;a=(t1+t2)>>>0;}[a,b,c,d,e,f,g,z].forEach((v,i)=>h[i]=(h[i]+v)>>>0);}
  return h.map(v=>v.toString(16).padStart(8,'0')).join('');
}
export function identityTargetRevision(p:Project,d:IdentityDirection):string{
  const selected=new Set(d.frameIds);let changed=true;while(changed){changed=false;for(const n of p.nodes)if(n.parentId&&selected.has(n.parentId)&&!selected.has(n.id)){selected.add(n.id);changed=true;}}
  return identityHash(JSON.stringify({direction:d,nodes:p.nodes.filter(n=>selected.has(n.id)),themes:p.designThemes,theme:p.theme,activeThemeId:p.activeThemeId,styles:d.styleIds.map(id=>p.stylePackages?.[id]??null),brief:p.identityLab?.brief,references:(d.referenceIds??[]).map(id=>p.identityLab?.references.find(r=>r.id===id)??null)}));
}
export function validateIdentityEvidence(p:Project,d:IdentityDirection,targetRevision:string,input:unknown):asserts input is IdentityEvidence[]{
  list(input,'evidence',12,evidence);if(!(input as IdentityEvidence[]).length)throw new Error('Revisión requiere renders reales.');
  const seen=new Set<string>();for(const e of input as IdentityEvidence[]){if(e.revision!==targetRevision||!d.frameIds.includes(e.frameId)||!p.nodes.some(n=>n.id===e.frameId&&n.type==='frame')||seen.has(e.frameId))throw new Error('Evidencia no corresponde a la dirección y revisión exactas.');seen.add(e.frameId);}
  if(d.frameIds.some(id=>!seen.has(id)))throw new Error('Falta render de una pantalla de la dirección.');
}
function target(p:Project,lab:IdentityLab,directionId:string){const d=lab.directions.find(d=>d.id===directionId);if(!d)throw new Error('Dirección no encontrada.');return d;}
function ownedNodes(p:Project,d:IdentityDirection,nodeIds:string[]){for(const id of nodeIds){let node=p.nodes.find(n=>n.id===id);const seen=new Set<string>();while(node&&!d.frameIds.includes(node.id)&&node.parentId&&!seen.has(node.id)){seen.add(node.id);node=p.nodes.find(n=>n.id===node!.parentId);}if(!node||!d.frameIds.includes(node.id))throw new Error('La selección no pertenece a las pantallas de la dirección.');}}
export function applyIdentityOperation(p:Project,input:IdentityOperation){
  const op=record(input,'operación'),name=op.op,lab=p.identityLab??emptyIdentityLab();
  const put=<T extends {id:string}>(items:T[],value:T)=>{const index=items.findIndex(v=>v.id===value.id);if(index<0)items.push(copy(value));else items[index]=copy(value);};
  switch(name){
    case 'identity.brief.set':{const patch=record(op.patch,'patch');keys(patch,['intent','audience','context','qualities','avoid','constraints'],'patch');const next={...lab.brief,...patch};validateIdentityBrief(next);lab.brief=copy(next);break;}
    case 'identity.reference.put':reference(op.reference,'reference');put(lab.references,op.reference as IdentityLab['references'][number]);break;
    case 'identity.reference.remove':id(op.id,'id');if(!lab.references.some(r=>r.id===op.id))throw new Error('Referencia no encontrada.');lab.references=lab.references.filter(r=>r.id!==op.id);break;
    case 'identity.direction.put':{direction(op.direction,'direction');const d=op.direction as IdentityDirection;for(const id of d.frameIds)if(!p.nodes.some(n=>n.id===id&&n.type==='frame'&&n.parentId===null))throw new Error('Dirección requiere pantallas raíz existentes.');for(const id of d.styleIds)if(!Object.hasOwn(p.stylePackages??{},id))throw new Error('Estilo no encontrado.');for(const id of d.referenceIds??[])if(!lab.references.some(r=>r.id===id))throw new Error('Referencia no encontrada.');put(lab.directions,d);break;}
    case 'identity.direction.remove':id(op.id,'id');target(p,lab,op.id as string);lab.directions=lab.directions.filter(d=>d.id!==op.id);break;
    case 'identity.decision.add':decision(op.decision,'decision');if((op.decision as {directionId?:string}).directionId)target(p,lab,(op.decision as {directionId:string}).directionId);if(lab.decisions.some(d=>d.id===(op.decision as {id:string}).id))throw new Error('Una decisión histórica no puede reemplazarse. Añade otra.');lab.decisions.push(copy(op.decision as IdentityLab['decisions'][number]));break;
    case 'identity.critique.add':{critique(op.critique,'critique');const c=op.critique as IdentityLab['critiques'][number],d=target(p,lab,c.directionId),rev=identityTargetRevision({...p,identityLab:lab},d);if(c.targetRevision!==rev)throw new Error('La revisión visual quedó obsoleta.');validateIdentityEvidence(p,d,rev,c.evidence);for(const f of c.findings)ownedNodes(p,d,f.nodeIds);if(lab.critiques.some(r=>r.id===c.id))throw new Error('Crítica repetida.');lab.critiques.push(copy(c));break;}
    case 'identity.refinement.put':{refinement(op.refinement,'refinement');const r=op.refinement as IdentityLab['refinements'][number],d=target(p,lab,r.directionId);if(r.targetRevision!==identityTargetRevision({...p,identityLab:lab},d))throw new Error('El refinamiento quedó obsoleto.');ownedNodes(p,d,r.nodeIds);put(lab.refinements,r);break;}
    default:throw new Error('Operación Identity Lab desconocida.');
  }
  validateIdentityLab(lab);p.identityLab=lab;
}
export function identityIssues(p:Project):IdentityIssue[]{
  const lab=p.identityLab;if(!lab)return [];const issues:IdentityIssue[]=[],revisions=new Map<string,string>();
  const targetRevision=(d:IdentityDirection)=>{let value=revisions.get(d.id);if(!value){value=identityTargetRevision(p,d);revisions.set(d.id,value);}return value;};
  const add=(kind:IdentityIssue['kind'],id:string,targetId:string,message:string)=>issues.push({kind,id,targetId,message});
  for(const d of lab.directions){for(const id of d.frameIds)if(!p.nodes.some(n=>n.id===id&&n.type==='frame'&&n.parentId===null))add('missing_frame',d.id,id,'Pantalla ausente.');for(const id of d.styleIds)if(!Object.hasOwn(p.stylePackages??{},id))add('missing_style',d.id,id,'Estilo ausente.');for(const id of d.referenceIds??[])if(!lab.references.some(r=>r.id===id))add('missing_reference',d.id,id,'Referencia ausente.');}
  for(const r of [...lab.critiques,...lab.refinements]){const d=lab.directions.find(d=>d.id===r.directionId);if(!d){add('missing_direction',r.id,r.directionId,'La dirección fue eliminada; el historial permanece.');continue;}if(targetRevision(d)!==r.targetRevision)add('evidence' in r?'stale_review':'stale_refinement',r.id,d.id,'El diseño o el brief cambió desde esta revisión.');if('evidence' in r&&targetRevision(d)===r.targetRevision){try{validateIdentityEvidence(p,d,r.targetRevision,r.evidence);for(const f of r.findings)ownedNodes(p,d,f.nodeIds);}catch{add('stale_review',r.id,d.id,'La evidencia no cubre la dirección o contiene vínculos incompatibles.');}}const nodeIds='findings' in r?r.findings.flatMap(f=>f.nodeIds):r.nodeIds;for(const id of nodeIds)if(!p.nodes.some(n=>n.id===id))add('missing_node',r.id,id,'La capa ya no existe.');}
  for(const d of lab.decisions)if(d.directionId&&!lab.directions.some(v=>v.id===d.directionId))add('missing_direction',d.id,d.directionId,'La dirección fue eliminada; la decisión permanece.');
  return issues;
}
export function exportIdentityPackage(p:Project):IdentityPackage {return copy({format:'codaru-identity-package/1',lab:p.identityLab??emptyIdentityLab(),document:p,issues:identityIssues(p)});}
