import type { Project } from './model';
import type { DesignStylePackage } from './contracts';
import { defaultDesignTheme, validateDesignThemes } from './themes';

const idPattern=/^[A-Za-z0-9][A-Za-z0-9_-]{0,79}$/;
const reserved=new Set(['project','constructor','prototype','__proto__']);
const object=(v:unknown):v is Record<string,unknown>=>!!v && typeof v==='object' && !Array.isArray(v);
const text=(v:unknown,max:number)=>typeof v==='string' && !!v.trim() && v.length<=max && !/[\u0000-\u001f]/.test(v);
const guidanceKeys=['composition','typography','controls','mobile','motion','avoid'] as const;
function lines(v:unknown) { return Array.isArray(v) && v.length<=24 && v.every(item=>text(item,1200)); }
export function parseStylePackage(input:unknown):DesignStylePackage {
  if(!object(input) || Object.keys(input).some(k=>!['format','id','name','version','description','theme','guidance','aru'].includes(k)) || input.format!=='codaru-style/1' || typeof input.id!=='string' || !idPattern.test(input.id) || reserved.has(input.id) || !text(input.name,160) || !text(input.version,40) || !text(input.description,2000) || !object(input.guidance) || Object.keys(input.guidance).some(k=>!guidanceKeys.includes(k as never)) || guidanceKeys.some(k=>!lines((input.guidance as Record<string,unknown>)[k]))) throw new Error('Paquete de estilo inválido: usa codaru-style/1, tokens y guías de composición, tipografía, controles, móvil, movimiento y elementos a evitar.');
  if (!object(input.theme) || input.theme.id!==input.id) throw new Error('El ID del tema debe coincidir con el del estilo.');
  const base=defaultDesignTheme();
  validateDesignThemes({format:'codaru-mockup',version:2,name:'Style validation',theme:'light',themes:{light:base.modes.light.colors,dark:base.modes.dark.colors},designThemes:{project:base,[input.id]:input.theme},activeThemeId:input.id,nodes:[],components:[]} as Project);
  if(input.aru!==undefined && (!object(input.aru) || Object.keys(input.aru).some(k=>!['palette','instructions'].includes(k)) || !Array.isArray(input.aru.palette) || input.aru.palette.length>32 || input.aru.palette.some(c=>typeof c!=='string' || !/^#[\da-f]{6}$/i.test(c)) || !lines(input.aru.instructions))) throw new Error('ARU: declara una paleta hexadecimal y guías de dibujo, sin comandos ni scripts.');
  return structuredClone(input) as unknown as DesignStylePackage;
}
export function validateStylePackages(input:unknown):asserts input is Record<string,DesignStylePackage> {
  if(!object(input) || Object.keys(input).length>100) throw new Error('El catálogo admite hasta 100 estilos portátiles.');
  for(const [id,value] of Object.entries(input))if(parseStylePackage(value).id!==id)throw new Error('ID de estilo inconsistente.');
}
export function importStylePackage(p:Project,input:unknown) {
  const style=parseStylePackage(input);
  if(!p.stylePackages) p.stylePackages={};
  if(Object.keys(p.stylePackages).length>=100 && !Object.hasOwn(p.stylePackages,style.id))throw new Error('El catálogo admite hasta 100 estilos portátiles.');
  p.stylePackages[style.id]=style;return style.id;
}
export function applyStylePackage(p:Project,id:string,frameId?:string,mode?:Project['theme']) {
  const style=p.stylePackages?.[id];if(!style)throw new Error('Estilo no encontrado. Consulta catalog --kind styles.');
  if(mode!==undefined && !['light','dark'].includes(mode))throw new Error('Modo de estilo inválido.');
  if(frameId!==undefined && (typeof frameId!=='string'||!frameId))throw new Error('Pantalla inválida.');
  const frame=frameId?p.nodes.find(n=>n.id===frameId):undefined;
  if(frameId && (!frame || frame.type!=='frame'))throw new Error('El estilo se aplica a una pantalla o al proyecto.');
  const themeId=`style-${style.id}`, theme=structuredClone(style.theme);theme.id=themeId;
  p.designThemes[themeId]=theme;
  if(frame){frame.themeId=themeId;if(mode)frame.themeMode=mode;}
  else {p.activeThemeId=themeId;if(mode)p.theme=mode;}
  // No positions, hierarchy or controls are generated by a theme switch.
}
export function styleSummaries(p:Project) {return Object.values(p.stylePackages??{}).map(s=>({id:s.id,name:s.name,version:s.version,description:s.description,themeId:`style-${s.id}`,applied:!!p.designThemes[`style-${s.id}`]}));}

export type { DesignStylePackage } from './contracts';
